In [33]:
import os
os.environ["OPENBLAS_NUM_THREADS"] = "1"
os.environ["MKL_NUM_THREADS"] = "1"
os.environ["OMP_NUM_THREADS"] = "1"
from mpi4py import MPI
import pickle


# torch
import torch
import torch.nn as nn

# quimb
import quimb.tensor as qtn
import autoray as ar

from vmc_torch.experiment.tn_model import *
from vmc_torch.variational_state import Variational_State
# from vmc_torch.hamiltonian import spinful_Fermi_Hubbard_square_lattice
from vmc_torch.hamiltonian_torch import spinful_Fermi_Hubbard_square_lattice_torch
from vmc_torch.torch_utils import SVD,QR
from vmc_torch.fermion_utils import generate_random_fpeps
from vmc_torch.utils import closest_divisible

# Register safe SVD and QR functions to torch
ar.register_function('torch','linalg.svd',SVD.apply)
ar.register_function('torch','linalg.qr',QR.apply)

from vmc_torch.global_var import DEBUG


COMM = MPI.COMM_WORLD
SIZE = COMM.Get_size()
RANK = COMM.Get_rank()

# Hamiltonian parameters
Lx = int(8)
Ly = int(8)
symmetry = 'Z2'
t = 1.0
U = 8.0
N_f = int(Lx*Ly)
n_fermions_per_spin = (N_f//2, N_f//2)
H = spinful_Fermi_Hubbard_square_lattice_torch(Lx, Ly, t, U, N_f, pbc=False, n_fermions_per_spin=n_fermions_per_spin)
graph = H.graph
# TN parameters
D = 4
chi = 200
dtype=torch.float64

# Load PEPS
pwd = '/pscratch/sd/s/sijingdu/VMC/fermion/data'
try:
    skeleton = pickle.load(open(f"{pwd}/{Lx}x{Ly}/t={t}_U={U}/N={N_f}/{symmetry}/D={D}/peps_skeleton.pkl", "rb"))
    peps_params = pickle.load(open(f"{pwd}/{Lx}x{Ly}/t={t}_U={U}/N={N_f}/{symmetry}/D={D}/peps_su_params.pkl", "rb"))
    peps = qtn.unpack(peps_params, skeleton)
except:
    peps = generate_random_fpeps(Lx, Ly, D=D, seed=2, symmetry=symmetry, Nf=N_f, spinless=False)[0]
peps.exponent = 0
peps_np = peps.copy()
peps.apply_to_arrays(lambda x: torch.tensor(x, dtype=dtype))
for ts in peps.tensors:
    ts.data.phase_sync(inplace=True)

# VMC sample size
N_samples = 2
N_samples = closest_divisible(N_samples, SIZE)

In [34]:
# from vmc_torch.experiment.tn_model import wavefunctionModel
# import ast
# import cotengra as ctg
# class fTNModel_reuse(wavefunctionModel):
#     def __init__(self, ftn, max_bond=None, dtype=torch.float32, functional=False, debug=False):
#         super().__init__()
#         self.param_dtype = dtype
#         self.functional = functional
#         self.debug = debug
#         # extract the raw arrays and a skeleton of the TN
#         params, self.skeleton = qtn.pack(ftn)
#         self.skeleton.exponent = 0

#         # Flatten the dictionary structure and assign each parameter as a part of a ModuleDict
#         self.torch_tn_params = nn.ModuleDict({
#             str(tid): nn.ParameterDict({
#                 str(sector): nn.Parameter(data)
#                 for sector, data in blk_array.items()
#             })
#             for tid, blk_array in params.items()
#         })

#         # Get symmetry
#         self.symmetry = ftn.arrays[0].symmetry

#         # Store the shapes of the parameters
#         self.param_shapes = [param.shape for param in self.parameters()]

#         self.model_structure = {
#             f'fPEPS (chi={max_bond})':{'D': ftn.max_bond(), 'Lx': ftn.Lx, 'Ly': ftn.Ly, 'symmetry': self.symmetry},
#         }
#         if max_bond is None or max_bond <= 0:
#             max_bond = None
#         self.max_bond = max_bond
#         self.tree = None
#         self.Lx = ftn.Lx
#         self.Ly = ftn.Ly
#         self._env_x_cache = None
#         self._env_y_cache = None
#         self.config_ref = None
#         self.amp_ref = None
    
#     def from_1d_to_2d(self, config, ordering='snake'):
#         if ordering == 'snake':
#             config_2d = config.reshape((self.Lx, self.Ly))
#             return config_2d
#         else:
#             raise NotImplementedError(f'Ordering {ordering} is not implemented.')
        
#     def from_1dsite_to_2dsite(self, site, ordering='snake'):
#         """
#             Convert a 1d site index to a 2d site index.
#             site: 1d site index
#         """
#         if ordering == 'snake':
#             return (site // self.Ly, site % self.Ly)
#         else:
#             raise ValueError(f"Unsupported ordering: {ordering}")
    
#     def transform_quimb_env_x_key_to_config_key(self, env_x, config):
#         """
#             Return a dictionary with the keys of of the config rows
#         """
#         config_2d = self.from_1d_to_2d(config)
#         env_x_row_config = {}
#         for key in env_x.keys():
#             if key[0] == 'xmax': # from bottom to top
#                 row_n = key[1]
#                 if row_n != self.Lx-1:
#                     rows_config = tuple(torch.cat(tuple(config_2d[row_n+1:].to(torch.int))).tolist())
#                     env_x_row_config[('xmax', rows_config)] = env_x[key]
#             elif key[0] == 'xmin': # from top to bottom
#                 row_n = key[1]
#                 if row_n != 0:
#                     rows_config = tuple(torch.cat(tuple(config_2d[:row_n].to(torch.int))).tolist())
#                     env_x_row_config[('xmin', rows_config)] = env_x[key]
#         return env_x_row_config
    
#     def transform_quimb_env_y_key_to_config_key(self, env_y, config):
#         """
#             Return a dictionary with the keys of of the config rows
#         """
#         config_2d = self.from_1d_to_2d(config)
#         env_y_row_config = {}
#         for key in env_y.keys():
#             if key[0] == 'ymax':
#                 col_n = key[1]
#                 if col_n != self.Ly-1:
#                     cols_config = tuple(torch.cat(tuple(config_2d[:, col_n+1:].to(torch.int))).tolist())
#                     env_y_row_config[('ymax', cols_config)] = env_y[key]
#             elif key[0] == 'ymin':
#                 col_n = key[1]
#                 if col_n != 0:
#                     cols_config = tuple(torch.cat(tuple(config_2d[:, :col_n].to(torch.int))).tolist())
#                     env_y_row_config[('ymin', cols_config)] = env_y[key]
#         return env_y_row_config

#     def cache_env_x(self, amp, config):
#         """
#             Cache the environment x for the given configuration
#         """
#         env_x = amp.compute_x_environments(max_bond=self.max_bond, cutoff=0.0)
#         env_x_cache = self.transform_quimb_env_x_key_to_config_key(env_x, config)
#         self._env_x_cache = env_x_cache
#         self.config_ref = config
#         self.amp_ref = amp
    
#     def cache_env_y(self, amp, config):
#         env_y = amp.compute_y_environments(max_bond=self.max_bond, cutoff=0.0)
#         env_y_cache = self.transform_quimb_env_y_key_to_config_key(env_y, config)
#         self._env_y_cache = env_y_cache
#         self.config_ref = config
#         self.amp_ref = amp
    
#     def cache_env(self, amp, config):
#         """
#             Cache the environment x and y for the given configuration
#         """
#         self.cache_env_x(amp, config)
#         self.cache_env_y(amp, config)
        
#     @property
#     def env_x_cache(self):
#         """
#             Return the cached environment x
#         """
#         if hasattr(self, '_env_x_cache'):
#             return self._env_x_cache
#         else:
#             return None
        
#     @property
#     def env_y_cache(self):
#         """
#             Return the cached environment y
#         """
#         if hasattr(self, '_env_y_cache'):
#             return self._env_y_cache
#         else:
#             return None
    
#     def clear_env_x_cache(self):
#         """
#             Clear the cached environment x
#         """
#         self._env_x_cache = None

#     def clear_env_y_cache(self):
#         """
#             Clear the cached environment y
#         """
#         self._env_y_cache = None
    
#     def clear_wavefunction_env_cache(self):
#         self.clear_env_x_cache()
#         self.clear_env_y_cache()
#         self.config_ref = None
#         self.amp_ref = None
    
#     def detect_changed_sites(self, config_ref, new_config):
#         """
#             Detect the sites that have changed in the new configuration,
#             written in 1d coordinate format.
#         """
#         changed_sites = set()
#         unchanged_sites = set()
#         for i in range(self.Lx * self.Ly):
#             if config_ref[i] != new_config[i]:
#                 changed_sites.add(i)
#             else:
#                 unchanged_sites.add(i)
#         changed_sites = sorted(changed_sites)
#         unchanged_sites = sorted(unchanged_sites)
#         if len(changed_sites) == 0:
#             return [], []
#         return changed_sites, unchanged_sites

#     def from_1d_sites_to_tids(self, sites):
#         """
#             Convert a list of 1d site indices to a list of tensor ids.
#         """
#         tids_list = list(self.skeleton.tensor_map.keys())
#         return [tids_list[site] for site in sites]
    
#     def detect_changed_rows(self, config_ref, new_config):
#         """
#             Detect the rows that have changed in the new configuration
#         """
#         config_ref_2d = self.from_1d_to_2d(config_ref)
#         new_config_2d = self.from_1d_to_2d(new_config)
#         changed_rows = []
#         for i in range(self.Lx):
#             if not torch.equal(config_ref_2d[i], new_config_2d[i]):
#                 changed_rows.append(i)
#         if len(changed_rows) == 0:
#             return [], [], []
#         unchanged_rows_above = list(range(changed_rows[0]))
#         unchanged_rows_below = list(range(changed_rows[-1]+1, self.Lx))
#         return changed_rows, unchanged_rows_above, unchanged_rows_below
    
#     def detect_changed_cols(self, config_ref, new_config):
#         """
#             Detect the columns that have changed in the new configuration
#         """
#         config_ref_2d = self.from_1d_to_2d(config_ref)
#         new_config_2d = self.from_1d_to_2d(new_config)
#         changed_cols = []
#         for i in range(self.Ly):
#             if not torch.equal(config_ref_2d[:, i], new_config_2d[:, i]):
#                 changed_cols.append(i)
#         if len(changed_cols) == 0:
#             return [], [], []
#         unchanged_cols_left = list(range(changed_cols[0]))
#         unchanged_cols_right = list(range(changed_cols[-1]+1, self.Ly))
#         return changed_cols, unchanged_cols_left, unchanged_cols_right
    
#     def update_env_x_cache(self, config):
#         """
#             Update the cached environment x for the given configuration
#         """
#         if self.env_x_cache is not None:
#             self.clear_env_x_cache()
#         amp_tn = self.get_amp_tn(config)
#         self.cache_env_x(amp_tn, config)
#         self.config_ref = config
#         self.amp_ref = amp_tn
    
#     def update_env_x_cache_to_row(self, config, row_id, from_which='xmin'):
#         amp_tn = self.get_amp_tn(config)
#         new_env_x = amp_tn.compute_environments(max_bond=self.max_bond, cutoff=0.0, xrange=(0, row_id+1) if from_which=='xmin' else (row_id-1, self.Lx-1), from_which=from_which)
#         new_env_x_cache = self.transform_quimb_env_x_key_to_config_key(new_env_x, config)
#         # add the new env_x to the cache
#         if self.env_x_cache is None:
#             self._env_x_cache = new_env_x_cache
#         else:
#             self._env_x_cache.update(new_env_x_cache)
#         self.config_ref = config
#         self.amp_ref = amp_tn
    
#     def update_env_y_cache(self, config):
#         """
#             Update the cached environment y for the given configuration
#         """
#         if self.env_y_cache is not None:
#             self.clear_env_y_cache()
#         amp_tn = self.get_amp_tn(config)
#         self.cache_env_y(amp_tn, config)
#         self.config_ref = config
#         self.amp_ref = amp_tn
    
#     def update_env_y_cache_to_col(self, config, col_id, from_which='ymin'):
#         amp_tn = self.get_amp_tn(config)
#         new_env_y = amp_tn.compute_environments(max_bond=self.max_bond, cutoff=0.0, yrange=(0, col_id+1) if from_which=='ymin' else (col_id-1, self.Ly-1), from_which=from_which)
#         new_env_y_cache = self.transform_quimb_env_y_key_to_config_key(new_env_y, config)
#         # add the new env_y to the cache
#         if self.env_y_cache is None:
#             self._env_y_cache = new_env_y_cache
#         else:
#             self._env_y_cache.update(new_env_y_cache)
#         self.config_ref = config
#         self.amp_ref = amp_tn
    
#     def psi(self):
#         """
#             Return the wavefunction (fPEPS)
#         """
#         # Reconstruct the original parameter structure (by unpacking from the flattened dict)
#         params = {
#             int(tid): {
#                 ast.literal_eval(sector): data
#                 for sector, data in blk_array.items()
#             }
#             for tid, blk_array in self.torch_tn_params.items()
#         }
#         # Reconstruct the TN with the new parameters
#         psi = qtn.unpack(params, self.skeleton)
#         return psi

#     def get_local_amp_tensors(self, sites:list, config:torch.Tensor):
#         """
#             Get the local tensors for the given tensor ids and configuration.
#             tids: a list of tensor ids. list of int.
#             config: the input configuration.
#         """
#         # first pick out the tensor parameters and form the local tn parameters vector
#         local_ts_params = {}
#         tids = self.from_1d_sites_to_tids(sites)
#         for tid in tids:
#             local_ts_params[tid] = {
#                 ast.literal_eval(sector): data
#                 for sector, data in self.torch_tn_params[str(tid)].items()
#             }
        
#         # Get sites corresponding to the tids
#         sites_2d = [self.from_1dsite_to_2dsite(site) for site in sites]

#         # Select the corresponding tensor skeleton
#         local_ts_skeleton = self.skeleton.select([self.skeleton.site_tag_id.format(*site) for site in sites_2d], which='any')

#         # Reconstruct the TN with the new parameters
#         local_ftn = qtn.unpack(local_ts_params, local_ts_skeleton)

#         # Fix the physical indices
#         return local_ftn.fix_phys_inds(sites_2d, config[sites])
    
#     def get_amp_tn(self, config, reconstruct=False):

#         if self.amp_ref is None or reconstruct:
#             psi = self.psi()
#             # Check config type
#             if not type(config) == torch.Tensor:
#                 config = torch.tensor(config, dtype=torch.int if self.functional else self.param_dtype)
#             else:
#                 if config.dtype != self.param_dtype:
#                     config = config.to(torch.int if self.functional else self.param_dtype)
#             # Get the amplitude
#             amp_tn = psi.get_amp(config, conj=True, functional=self.functional)
#             return amp_tn
        
#         else:
#             # detect the sites that have changed
#             changed_sites, unchanged_sites = self.detect_changed_sites(self.config_ref, config)

#             if len(changed_sites) == 0:
#                 return self.amp_ref
#             else:
#                 # substitute the changed sites tensors
#                 local_amp_tn = self.get_local_amp_tensors(changed_sites, config)
#                 unchanged_sites_2d = [self.from_1dsite_to_2dsite(site) for site in unchanged_sites]
#                 unchanged_sites_tags = [self.skeleton.site_tag_id.format(*site) for site in unchanged_sites_2d]
#                 unchanged_amp_tn = self.amp_ref.select(unchanged_sites_tags, which='any')
#                 # merge the local_amp_tn and unchanged_amp_tn
#                 amp_tn = local_amp_tn | unchanged_amp_tn
#                 return amp_tn
    
#     def amplitude(self, x):
#         # Reconstruct the original parameter structure (by unpacking from the flattened dict)
#         params = {
#             int(tid): {
#                 ast.literal_eval(sector): data
#                 for sector, data in blk_array.items()
#             }
#             for tid, blk_array in self.torch_tn_params.items()
#         }
#         # Reconstruct the TN with the new parameters
#         psi = qtn.unpack(params, self.skeleton)
#         # `x` is expected to be batched as (batch_size, input_dim)
#         # Loop through the batch and compute amplitude for each sample
#         batch_amps = []
#         for x_i in x:
#             # Check x_i type
#             if not type(x_i) == torch.Tensor:
#                 x_i = torch.tensor(x_i, dtype=torch.int if self.functional else self.param_dtype)
#             else:
#                 if x_i.dtype != self.param_dtype:
#                     x_i = x_i.to(torch.int if self.functional else self.param_dtype)
#             # Get the amplitude
#             # amp = psi.get_amp(x_i, conj=True, functional=self.functional)
#             amp = self.get_amp_tn(x_i)

#             if self.max_bond is None:
#                 amp = amp
#                 if self.tree is None:
#                     opt = ctg.HyperOptimizer(progbar=True, max_repeats=10, parallel=True)
#                     self.tree = amp.contraction_tree(optimize=opt)
#                 amp_val = amp.contract(optimize=self.tree)

#             else:
#                 if self.cache_env_mode:
#                     self.cache_env_x(amp, x_i)
#                     # self.cache_env_y(amp, x_i)
#                     self.config_ref = x_i
#                     config_2d = self.from_1d_to_2d(x_i)
#                     key_bot = ('xmax', tuple(torch.cat(tuple(config_2d[self.Lx//2:].to(torch.int))).tolist()))
#                     key_top = ('xmin', tuple(torch.cat(tuple(config_2d[:self.Lx//2].to(torch.int))).tolist()))
#                     amp_bot = self.env_x_cache[key_bot]
#                     amp_top = self.env_x_cache[key_top]
#                     amp_val = (amp_bot|amp_top).contract()
                    

#                 else:
#                     if self.env_x_cache is None and self.env_y_cache is None:
#                         # check whether we can reuse the cached environment
#                         amp = amp.contract_boundary_from_ymin(max_bond=self.max_bond, cutoff=0.0, yrange=[0, psi.Ly//2-1])
#                         amp = amp.contract_boundary_from_ymax(max_bond=self.max_bond, cutoff=0.0, yrange=[psi.Ly//2, psi.Ly-1])
#                         amp_val = amp.contract()
#                     else:
#                         config_2d = self.from_1d_to_2d(x_i)
#                         # detect the rows that have changed
#                         changed_rows, unchanged_rows_above, unchanged_rows_below = self.detect_changed_rows(self.config_ref, x_i)
#                         # detect the columns that have changed
#                         changed_cols, unchanged_cols_left, unchanged_cols_right = self.detect_changed_cols(self.config_ref, x_i)
#                         if len(changed_rows) == 0:
#                             key_bot = ('xmax', tuple(torch.cat(tuple(config_2d[self.Lx//2:].to(torch.int))).tolist()))
#                             key_top = ('xmin', tuple(torch.cat(tuple(config_2d[:self.Lx//2].to(torch.int))).tolist()))
#                             amp_bot = self.env_x_cache[key_bot]
#                             amp_top = self.env_x_cache[key_top]
#                             amp_val = (amp_bot|amp_top).contract()
#                         else:
#                             if len(changed_rows) <= len(changed_cols):
#                                 # for bottom envs, until the last row in the changed rows, we can reuse the env
#                                 # for top envs, until the first row in the changed rows, we can reuse the env
#                                 amp_changed_rows = qtn.TensorNetwork([amp.select(amp.x_tag_id.format(row_n)) for row_n in changed_rows])
#                                 amp_unchanged_bottom_env = qtn.TensorNetwork()
#                                 amp_unchanged_top_env = qtn.TensorNetwork()
#                                 if len(unchanged_rows_below) != 0:
#                                     amp_unchanged_bottom_env = self.env_x_cache[('xmax', tuple(torch.cat(tuple(config_2d[unchanged_rows_below].to(torch.int))).tolist()))]
#                                 if len(unchanged_rows_above) != 0:
#                                     amp_unchanged_top_env = self.env_x_cache[('xmin', tuple(torch.cat(tuple(config_2d[unchanged_rows_above].to(torch.int))).tolist()))]
#                                 amp_val = (amp_unchanged_bottom_env|amp_unchanged_top_env|amp_changed_rows).contract()
#                                 # print(f'changed rows: {changed_rows}', self.from_1d_to_2d(x_i), self.from_1d_to_2d(self.config_ref))
#                             else:
#                                 # for left envs, until the first column in the changed columns, we can reuse the env
#                                 # for right envs, until the last column in the changed columns, we can reuse the env
#                                 amp_changed_cols = qtn.TensorNetwork([amp.select(amp.y_tag_id.format(col_n)) for col_n in changed_cols])
#                                 amp_unchanged_left_env = qtn.TensorNetwork()
#                                 amp_unchanged_right_env = qtn.TensorNetwork()
#                                 if len(unchanged_cols_left) != 0:
#                                     amp_unchanged_left_env = self.env_y_cache[('ymin', tuple(torch.cat(tuple(config_2d[:, unchanged_cols_left].to(torch.int))).tolist()))]
#                                 if len(unchanged_cols_right) != 0:
#                                     amp_unchanged_right_env = self.env_y_cache[('ymax', tuple(torch.cat(tuple(config_2d[:, unchanged_cols_right].to(torch.int))).tolist()))]
#                                 amp_val = (amp_unchanged_left_env|amp_unchanged_right_env|amp_changed_cols).contract()
                                
#             if amp_val==0.0:
#                 amp_val = torch.tensor(0.0)
            
#             if self.debug:
#                 print(f'Reused Amp val: {amp_val}, Exact Amp val: {self.get_amp_tn(x_i).contract()}')
            
#             batch_amps.append(amp_val)

#         # Return the batch of amplitudes stacked as a tensor
#         return torch.stack(batch_amps)

In [35]:
# reusable fPEPS model
random_x = torch.tensor(H.hilbert.random_state())
random_x1 = random_x.clone()
print(random_x)
random_x1[2] = 1
random_x1[3] = 2

# print((peps.product_bra_state(random_x).conj()|peps).contract(), (peps|peps.product_bra_state(random_x, reverse=1)).contract())

# permute_list = []
# for tensor in peps.product_bra_state(random_x).conj().tensors:
#     # print(tensor.data.charge, tensor.data.oddpos)
#     if len(tensor.data.oddpos)>0:
#         # print(tensor.data.oddpos[0].label, tensor.data.oddpos[0].dual)
#         permute_list.append(tensor.data.oddpos[0].label)

# # sort the list and note down the parity of the permutation
# print(len(permute_list))
# # sum from len(permute_list) to 1
# N = 0
# for i in range(len(permute_list)):
#     N += i
# print('phase correction from reversing the ordering:', (-1)**(N%2))

from vmc_torch.sampler import *

model = fTNModel_reuse(peps, max_bond=chi, dtype=dtype, debug=False)

sampled_x = torch.tensor([3, 1, 1, 0, 1, 2, 2, 0, 2, 3, 1, 1, 2, 2, 3, 2, 2, 3, 2, 0, 1, 3, 3, 2,
        2, 1, 1, 1, 0, 3, 0, 2, 3, 1, 1, 3, 0, 2, 1, 3, 1, 0, 0, 0, 2, 3, 0, 0,
        0, 1, 1, 0, 3, 3, 2, 2, 3, 3, 3, 0, 0, 2, 1, 0])

sampler = MetropolisExchangeSamplerSpinful_2D_reusable(H.hilbert, graph, N_samples=N_samples, burn_in_steps=1, reset_chain=False, random_edge=False, equal_partition=False, dtype=dtype)
# sampler = MetropolisExchangeSamplerSpinful(H.hilbert, graph, N_samples=N_samples, burn_in_steps=10, reset_chain=False, random_edge=False, equal_partition=False, dtype=dtype)
vstate = Variational_State(model, hi=H.hilbert, sampler=sampler, dtype=dtype)
# t0 = time.time()
# sampled_x, sampled_amp = sampler._sample_next(vstate, burn_in=False)
vstate.set_cache_env_mode(on=True)
amp, grad = vstate.amplitude_grad(sampled_x, retain_graph=True)
vstate.set_cache_env_mode(on=False)
# t1 = time.time()

tensor([0, 1, 0, 1, 2, 3, 1, 0, 1, 1, 3, 2, 2, 1, 2, 0, 3, 1, 0, 3, 2, 2, 3, 0,
        0, 3, 0, 0, 1, 2, 1, 3, 0, 2, 0, 2, 2, 0, 1, 3, 0, 0, 2, 1, 1, 3, 2, 2,
        3, 3, 3, 1, 3, 0, 0, 0, 3, 2, 2, 3, 3, 1, 1, 3])


In [36]:
from vmc_torch.fermion_utils import flatten_fts_params
from vmc_torch.fermion_utils import reconstruct_fts_params
amp_tn = model.get_amp_tn(sampled_x)
ts0 = amp_tn.select('I0,0').contract()
ts0.draw()
ts_params = flatten_fts_params(ts0.get_params())

ts_left = [ts for ts in amp_tn.tensors if 'I0,0' not in ts.tags]
tn_left = qtn.TensorNetwork(ts_left)
grad_ts = tn_left.contract()
grad_ts.data.phase_sync(inplace=True) # BUG: should take into account the fermion signs generated in the final contraction!!

grad_ts_params = flatten_fts_params(grad_ts.get_params())
# ts0.data.blocks, grad_ts.data.blocks

In [37]:
new_model = fTNModel_reuse(peps, max_bond=-1, dtype=dtype, debug=False)
new_amp = new_model(sampled_x)
new_model(sampled_x).backward(retain_graph=True)
for param in new_model.parameters():
    if param.grad is None:
        print(None)
    else:
        print(param.grad/new_amp)

  0%|          | 0/10 [00:00<?, ?it/s]

F=8.18 C=8.92 S=20.00 P=21.01: 100%|██████████| 10/10 [00:01<00:00,  8.99it/s]


tensor([[[0.0000e+00, 1.7516e+00],
         [0.0000e+00, 3.4465e+00]],

        [[0.0000e+00, 5.0189e-12],
         [0.0000e+00, 5.9945e-12]]], dtype=torch.float64,
       grad_fn=<DivBackward0>)
None
None
tensor([[[-0.0000e+00, -4.8799e-12],
         [-0.0000e+00, -2.1363e+00]],

        [[ 0.0000e+00,  3.7207e-12],
         [ 0.0000e+00,  4.0671e-01]]], dtype=torch.float64,
       grad_fn=<DivBackward0>)
None
tensor([[[[-4.4632e-03, -0.0000e+00],
          [-1.8323e-11, -0.0000e+00]],

         [[-1.3401e-03, -0.0000e+00],
          [-1.4479e-11, -0.0000e+00]]],


        [[[ 4.3731e-17,  0.0000e+00],
          [ 1.0967e-25,  0.0000e+00]],

         [[ 1.3130e-17,  0.0000e+00],
          [ 8.6801e-26,  0.0000e+00]]]], dtype=torch.float64,
       grad_fn=<DivBackward0>)
tensor([[[[-5.7129e-13, -0.0000e+00],
          [-5.4806e-15, -0.0000e+00]],

         [[ 6.6704e+00,  0.0000e+00],
          [ 1.2570e-01,  0.0000e+00]]],


        [[[ 3.2713e-27,  0.0000e+00],
          [ 3.7304e-29

In [38]:
grad_ts_params/amp

tensor([ 1.7516e+00,  3.4465e+00,  5.0193e-12,  5.9945e-12,  4.8818e-12,
         2.1363e+00, -3.7214e-12, -4.0671e-01], dtype=torch.float64,
       grad_fn=<DivBackward0>)

In [48]:
model.clear_grad()
# model._env_x_cache = None
# model._env_y_cache = None
amp_model = model(sampled_x)
amp_model.backward(retain_graph=True)
for param in model.parameters():
    if param.grad is None:
        print(None)
    else:
        print(param.grad/amp_model)

model.clear_grad()

tensor([[[0.0000e+00, 1.2071e+00],
         [0.0000e+00, 7.8829e-01]],

        [[0.0000e+00, 5.2951e-15],
         [0.0000e+00, 4.5705e-15]]], dtype=torch.float64,
       grad_fn=<DivBackward0>)
None
None
tensor([[[ 0.0000e+00,  2.8684e-14],
         [-0.0000e+00, -2.6596e+00]],

        [[-0.0000e+00, -9.7773e-15],
         [ 0.0000e+00,  9.7073e-01]]], dtype=torch.float64,
       grad_fn=<DivBackward0>)
None
tensor([[[[-1.7475e-03, -0.0000e+00],
          [-1.8168e-15, -0.0000e+00]],

         [[-5.4131e-04, -0.0000e+00],
          [-8.0855e-15, -0.0000e+00]]],


        [[[-1.4117e-17, -0.0000e+00],
          [-1.7648e-05, -0.0000e+00]],

         [[-3.0191e-18, -0.0000e+00],
          [-1.6110e-05, -0.0000e+00]]]], dtype=torch.float64,
       grad_fn=<DivBackward0>)
tensor([[[[-5.6384e-14, -0.0000e+00],
          [-6.1016e-16, -0.0000e+00]],

         [[ 5.8037e+00,  0.0000e+00],
          [ 6.2960e-02,  0.0000e+00]]],


        [[[-2.1008e-07, -0.0000e+00],
          [ 4.1875e-09

In [ ]:
config_2d = model.from_1d_to_2d(sampled_x)
model._env_x_cache = None
model._env_y_cache = None
model.cache_env_mode = True
model(sampled_x)
key_bot = ('xmax', tuple(torch.cat(tuple(config_2d[model.Lx//2:].to(torch.int))).tolist()))
key_top = ('xmin', tuple(torch.cat(tuple(config_2d[:model.Lx//2].to(torch.int))).tolist()))
amp_bot = model.env_x_cache[key_bot]
amp_top = model.env_x_cache[key_top]
amp_val = (amp_bot|amp_top).contract()*10**(model.skeleton.exponent)
amp_val.backward(retain_graph=True)

for param in model.parameters():
    if param.grad is None:
        print(None)
    else:
        print(param.grad/amp_model)
model.clear_grad()
print('amp_val:', amp_val)

In [70]:
model.get_amp_tn(sampled_x).contract().backward(retain_graph=True)
for param in model.parameters():
    if param.grad is None:
        print(None)
    else:
        print(param.grad/amp_model)
model.clear_grad()
print(model.get_amp_tn(sampled_x).contract())

tensor([[[0.0000e+00, 1.7516e+00],
         [0.0000e+00, 3.4465e+00]],

        [[0.0000e+00, 5.0194e-12],
         [0.0000e+00, 5.9951e-12]]], dtype=torch.float64,
       grad_fn=<DivBackward0>)
None
None
tensor([[[-0.0000e+00, -4.8811e-12],
         [-0.0000e+00, -2.1363e+00]],

        [[ 0.0000e+00,  3.7213e-12],
         [ 0.0000e+00,  4.0671e-01]]], dtype=torch.float64,
       grad_fn=<DivBackward0>)
None
tensor([[[[-4.4632e-03, -0.0000e+00],
          [-1.8325e-11, -0.0000e+00]],

         [[-1.3401e-03, -0.0000e+00],
          [-1.4482e-11, -0.0000e+00]]],


        [[[ 4.3731e-17,  0.0000e+00],
          [ 1.0968e-25,  0.0000e+00]],

         [[ 1.3130e-17,  0.0000e+00],
          [ 8.6815e-26,  0.0000e+00]]]], dtype=torch.float64,
       grad_fn=<DivBackward0>)
tensor([[[[-5.7145e-13, -0.0000e+00],
          [-5.4820e-15, -0.0000e+00]],

         [[ 6.6704e+00,  0.0000e+00],
          [ 1.2570e-01,  0.0000e+00]]],


        [[[ 3.2722e-27,  0.0000e+00],
          [ 3.7313e-29

In [17]:
average_rel_err = 0.0
for rel_contraction_err in model.debug_amp_cache:
    average_rel_err += rel_contraction_err[2]
average_rel_err /= len(model.debug_amp_cache)
print(f"Average relative contraction error: {average_rel_err} for D={D}, chi={chi}, time={t1-t0:.2f}s, Lx={Lx}, Ly={Ly}, symmetry={symmetry}")

Average relative contraction error: 3.0589315227787804e-14 for D=4, chi=200, time=35.31s, Lx=8, Ly=8, symmetry=Z2


Average relative contraction error: 1.7202865340398485 for D=4, chi=16, time=14.22s, Lx=8, Ly=8, symmetry=Z2
Average relative contraction error: 1.374601678306499 for D=4, chi=64, time=16.01s, Lx=8, Ly=8, symmetry=Z2
Average relative contraction error: 0.10715998841340528 for D=4, chi=128, time=15.06s, Lx=8, Ly=8, symmetry=Z2
Average relative contraction error: 0.0748252922749927 for D=4, chi=160, time=15.44s, Lx=8, Ly=8, symmetry=Z2
Average relative contraction error: 8.601565829643471e-14 for D=4, chi=256, time=16.54s, Lx=8, Ly=8, symmetry=Z2

In [48]:
# fPEPS w/o reuse
model1 = fTNModel(peps, max_bond=-1, dtype=dtype)
vstate1 = Variational_State(model1, hi=H.hilbert, sampler=sampler, dtype=dtype)
amp1, grad1 = vstate1.amplitude_grad(sampled_x)

F=8.52 C=9.27 S=22.00 P=22.32: 100%|██████████| 10/10 [00:00<00:00, 19.96it/s] 


In [49]:
assert torch.norm(grad-grad1)<10**(-3)*torch.norm(grad1), f'Gradients are not equal: {torch.norm(grad-grad1)}'
assert torch.norm(amp-amp1)<10**(-3)*torch.norm(amp1), f'Amplitudes are not equal w rel err: {torch.norm(amp-amp1)/ torch.norm(amp1)}'

AssertionError: Gradients are not equal: 0.04582833351407129

In [50]:
torch.norm(amp-amp1)/torch.norm(amp1), torch.norm(grad-grad1)/torch.norm(grad1)

(tensor(0.0010, dtype=torch.float64, grad_fn=<DivBackward0>),
 tensor(0.0058, dtype=torch.float64, grad_fn=<DivBackward0>))

In [101]:
# local energy w reuse
op = H
sigma = sampled_x
psi_sigma = amp
eta, O_etasigma = op.get_conn(sigma)
psi_eta = vstate.amplitude(eta)
psi_sigma = psi_sigma.cpu().detach().numpy()
psi_eta = psi_eta.cpu().detach().numpy()
op_loc = np.sum(O_etasigma * (psi_eta / psi_sigma), axis=-1)
print(f"Local energy with reuse: {op_loc}")

# local energy w/o reuse
op1 = H
sigma1 = sampled_x
psi_sigma1 = amp1
eta1, O_etasigma1 = op1.get_conn(sigma1)
psi_eta1 = vstate1.amplitude(eta1)
psi_sigma1 = psi_sigma1.cpu().detach().numpy()
psi_eta1 = psi_eta1.cpu().detach().numpy()
op_loc1 = np.sum(O_etasigma1 * (psi_eta1 / psi_sigma1), axis=-1)
print(f"Local energy w/o reuse: {op_loc1}")

Local energy with reuse: 117.2844806950575
Local energy w/o reuse: 117.3802497272778


In [14]:
graph.row_edges, graph.col_edges, graph.edges()

({0: [(0, 1), (1, 2), (2, 3), (3, 4), (4, 5)],
  1: [(6, 7), (7, 8), (8, 9), (9, 10), (10, 11)],
  2: [(12, 13), (13, 14), (14, 15), (15, 16), (16, 17)],
  3: [(18, 19), (19, 20), (20, 21), (21, 22), (22, 23)],
  4: [(24, 25), (25, 26), (26, 27), (27, 28), (28, 29)],
  5: [(30, 31), (31, 32), (32, 33), (33, 34), (34, 35)]},
 {0: [(0, 6), (6, 12), (12, 18), (18, 24), (24, 30)],
  1: [(1, 7), (7, 13), (13, 19), (19, 25), (25, 31)],
  2: [(2, 8), (8, 14), (14, 20), (20, 26), (26, 32)],
  3: [(3, 9), (9, 15), (15, 21), (21, 27), (27, 33)],
  4: [(4, 10), (10, 16), (16, 22), (22, 28), (28, 34)],
  5: [(5, 11), (11, 17), (17, 23), (23, 29), (29, 35)]},
 [(0, 1),
  (0, 6),
  (1, 2),
  (1, 7),
  (2, 3),
  (2, 8),
  (3, 4),
  (3, 9),
  (4, 5),
  (4, 10),
  (5, 11),
  (6, 7),
  (6, 12),
  (7, 8),
  (7, 13),
  (8, 9),
  (8, 14),
  (9, 10),
  (9, 15),
  (10, 11),
  (10, 16),
  (11, 17),
  (12, 13),
  (12, 18),
  (13, 14),
  (13, 19),
  (14, 15),
  (14, 20),
  (15, 16),
  (15, 21),
  (16, 17),
  (1

In [5]:
model = fTNModel_reuse(peps, max_bond=chi, dtype=dtype, functional=False)
model.cache_env_mode = True
model(random_x)
model.cache_env_mode = False

In [6]:
import time
t0 = time.time()
amp0 = model.get_amp_tn(random_x1)
t1 = time.time()
print("Time taken:", t1 - t0)
amp0.contract()

Time taken: 0.0023186206817626953


0.0

In [7]:
t0 = time.time()
amp1 = model.get_amp_tn(random_x1, reconstruct=True)
t1 = time.time()
print("Time taken:", t1 - t0)
amp1.contract()

Time taken: 0.011317729949951172


0.0

# mode = 'dm':
ImportError: autoray couldn't find function 'argsort' for backend 'symmray'.

##### TO-DO: need to implement eigh_truncate for fermionic tensors

# mode = 'fit'

In [9]:
amp0.contract_boundary_from_xmax(xrange=(0, model.Lx-1), max_bond=16, cutoff=0.0, mode='fit').contract()

TypeError: Expected FermionicArray, got <class 'numpy.ndarray'>.